compress -r arrival1.rpt
compress -r ChkLedgr.rpt
compress -r Commish1.rpt
compress -r Commish2.rpt
compress -r Commish3.rpt
compress -r conf.rpt
compress -r conf2.rpt
compress -r Daily1.rpt
compress -r Depart1.rpt
compress -r FeeSum.rpt
compress -r hstlngck.rpt
compress -r hstshtck.rpt
compress -r Label1.rpt
compress -r Label2.rpt
compress -r netsum.rpt
compress -r Notify1.rpt
compress -r PayRec1.rpt
compress -r PayDue1.rpt
compress -r Tax1099.rpt
compress -r refund1.rpt
compress -r svfeesum.rpt
compress -r acctlist.rpt
compress -r caractiv.rpt
compress -r sumrecd1.rpt
compress -r overpay.rpt
compress -r Avail1.rpt
compress -r bnbhelp.hlp
compress -r bnbhelp.cnt
compress -r bnb.exe
compress -r bnb1.mdb