// <auto-generated />
using System;
using BnB.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BnB.Data.Migrations
{
    [DbContext(typeof(BnBDbContext))]
    [Migration("20260117400000_AddPropertyPaymentPolicy")]
    partial class AddPropertyPaymentPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BnB.Core.Models.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Commission")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionReceived")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfirmationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DailyGrossRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DailyHostRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DiscountRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Forfeit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberInParty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfNights")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyAccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Suppress")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalTax")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitNameDescription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationNumber");

                    b.HasIndex("GuestId");

                    b.HasIndex("PropertyAccountNumber");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("BnB.Core.Models.CompanyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanyInfo");
                });

            modelBuilder.Entity("BnB.Core.Models.Fact", b =>
                {
                    b.Property<int>("FactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FactCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("FactId");

                    b.ToTable("Facts");
                });

            modelBuilder.Entity("BnB.Core.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Closure")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateBooked")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LabelFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referral")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReservationFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelingWith")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("BnB.Core.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedTo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CancellationFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancellationFeeDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfirmationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DefaultCommission")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DepositDue")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DepositDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OtherCredit")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrepaymentDue")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrepaymentDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedFrom")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RefundOwed")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationNumber");

                    b.HasIndex("GuestId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BnB.Core.Models.Property", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckTo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("DBA")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultCancellationNoticeDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DefaultCancellationFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CancellationProcessingFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultDepositDueDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DefaultDepositPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultPrepaymentDueDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepositRequired")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exceptions")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionsDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FederalTaxId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FuturePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FuturePercentDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPeakPeriodPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingCity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingFax")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingPhone1")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingPhone2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingState")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PeakPeriodCancellationNoticeDays")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PeakPeriodCancellationFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PeakPeriodEndDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeakPeriodEndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeakPeriodPrepaymentDueDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeakPeriodStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeakPeriodStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PercentToHost")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyCity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyFax")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyState")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SuppressFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxPlanCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("BnB.Core.Models.PropertyFact", b =>
                {
                    b.Property<int>("PropertyFactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PropertyFactId");

                    b.HasIndex("FactId");

                    b.HasIndex("PropertyId", "FactId")
                        .IsUnique();

                    b.ToTable("PropertyFacts");
                });

            modelBuilder.Entity("BnB.Core.Models.RoomBlackout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("RoomBlackouts");
                });

            modelBuilder.Entity("BnB.Core.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HostRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyAccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyAccountNumber");

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("BnB.Core.Models.TaxPlan", b =>
                {
                    b.Property<string>("PlanCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PlanCode");

                    b.ToTable("TaxPlans");
                });

            modelBuilder.Entity("BnB.Core.Models.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanCode");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("BnB.Core.Models.TravelAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TravelAgencies");
                });

            modelBuilder.Entity("BnB.Core.Models.TravelAgentBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CommissionAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CommissionPaidDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfirmationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TravelAgencyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("TravelAgencyId");

                    b.ToTable("TravelAgentBookings");
                });

            modelBuilder.Entity("BnB.Core.Models.Accommodation", b =>
                {
                    b.HasOne("BnB.Core.Models.Guest", "Guest")
                        .WithMany("Accommodations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnB.Core.Models.Property", "Property")
                        .WithMany("Accommodations")
                        .HasForeignKey("PropertyAccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BnB.Core.Models.Payment", b =>
                {
                    b.HasOne("BnB.Core.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("BnB.Core.Models.PropertyFact", b =>
                {
                    b.HasOne("BnB.Core.Models.Fact", "Fact")
                        .WithMany("PropertyFacts")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnB.Core.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fact");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BnB.Core.Models.RoomBlackout", b =>
                {
                    b.HasOne("BnB.Core.Models.RoomType", "RoomType")
                        .WithMany("Blackouts")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("BnB.Core.Models.RoomType", b =>
                {
                    b.HasOne("BnB.Core.Models.Property", "Property")
                        .WithMany("RoomTypes")
                        .HasForeignKey("PropertyAccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BnB.Core.Models.TravelAgentBooking", b =>
                {
                    b.HasOne("BnB.Core.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnB.Core.Models.TravelAgency", "TravelAgency")
                        .WithMany("Bookings")
                        .HasForeignKey("TravelAgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("TravelAgency");
                });

            modelBuilder.Entity("BnB.Core.Models.TaxRate", b =>
                {
                    b.HasOne("BnB.Core.Models.TaxPlan", "TaxPlan")
                        .WithMany("TaxRates")
                        .HasForeignKey("PlanCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxPlan");
                });

            modelBuilder.Entity("BnB.Core.Models.Fact", b =>
                {
                    b.Navigation("PropertyFacts");
                });

            modelBuilder.Entity("BnB.Core.Models.Guest", b =>
                {
                    b.Navigation("Accommodations");
                });

            modelBuilder.Entity("BnB.Core.Models.Property", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("BnB.Core.Models.RoomType", b =>
                {
                    b.Navigation("Blackouts");
                });

            modelBuilder.Entity("BnB.Core.Models.TaxPlan", b =>
                {
                    b.Navigation("TaxRates");
                });

            modelBuilder.Entity("BnB.Core.Models.TravelAgency", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
