// <auto-generated />
using System;
using BnB.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BnB.Data.Migrations
{
    [DbContext(typeof(BnBDbContext))]
    partial class BnBDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("BnB.Core.Models.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Commission")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionReceived")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfirmationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DailyGrossRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DailyNetRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Forfeit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NightNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Notified")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberInParty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfNights")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OverridePercentToHost")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("OverrideTaxPlanCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyAccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevisionDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ServiceFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Suppress")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Tax1")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tax2")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tax3")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalGrossWithTax")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalNetWithTax")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalTax")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitNameDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseManualAmounts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationNumber");

                    b.HasIndex("PropertyAccountNumber");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("BnB.Core.Models.CarAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarAgencies");
                });

            modelBuilder.Entity("BnB.Core.Models.CarRental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarAgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CommissionPaidDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfirmationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DailyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarAgencyId");

                    b.HasIndex("ConfirmationNumber");

                    b.ToTable("CarRentals");
                });

            modelBuilder.Entity("BnB.Core.Models.Check", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccommodationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVoid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayableTo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.ToTable("Checks");
                });

            modelBuilder.Entity("BnB.Core.Models.CheckNumberConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HostCheckNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MiscCheckNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SharedAccounts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TravelCheckNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CheckNumberConfigs");
                });

            modelBuilder.Entity("BnB.Core.Models.CommonText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("CommonTexts");
                });

            modelBuilder.Entity("BnB.Core.Models.CompanyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanyInfo");
                });

            modelBuilder.Entity("BnB.Core.Models.Guest", b =>
                {
                    b.Property<long>("ConfirmationNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessPhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Closure")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateBooked")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LabelFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referral")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReservationFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelingWith")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ConfirmationNumber");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("BnB.Core.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedTo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CancellationFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancellationFeeDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfirmationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DefaultCommission")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DepositDue")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DepositDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OtherCredit")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrepaymentDue")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrepaymentDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedFrom")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RefundOwed")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationNumber");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BnB.Core.Models.Property", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckTo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("DBA")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepositRequired")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exceptions")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionsDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FederalTaxId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FuturePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FuturePercentDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingCity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingFax")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingPhone1")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingPhone2")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingState")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentToHost")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyCity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyFax")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyPhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyState")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SuppressFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxPlanCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("BnB.Core.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DefaultRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyAccountNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PropertyAccountNumber");

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("BnB.Core.Models.TaxPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanTitle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanCode")
                        .IsUnique();

                    b.ToTable("TaxPlans");
                });

            modelBuilder.Entity("BnB.Core.Models.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FutureTaxOne")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FutureTaxOneEffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FutureTaxThree")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FutureTaxThreeEffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FutureTaxTwo")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FutureTaxTwoEffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxOne")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxOneDescription")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxThree")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxThreeDescription")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxTwo")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxTwoDescription")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("BnB.Core.Models.TravelAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TravelAgencies");
                });

            modelBuilder.Entity("BnB.Core.Models.TravelAgentBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CommissionPaidDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfirmationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TravelAgencyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationNumber");

                    b.HasIndex("TravelAgencyId");

                    b.ToTable("TravelAgentBookings");
                });

            modelBuilder.Entity("BnB.Core.Models.Accommodation", b =>
                {
                    b.HasOne("BnB.Core.Models.Guest", "Guest")
                        .WithMany("Accommodations")
                        .HasForeignKey("ConfirmationNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnB.Core.Models.Property", "Property")
                        .WithMany("Accommodations")
                        .HasForeignKey("PropertyAccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BnB.Core.Models.CarRental", b =>
                {
                    b.HasOne("BnB.Core.Models.CarAgency", "CarAgency")
                        .WithMany("Rentals")
                        .HasForeignKey("CarAgencyId");

                    b.HasOne("BnB.Core.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("ConfirmationNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarAgency");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("BnB.Core.Models.Check", b =>
                {
                    b.HasOne("BnB.Core.Models.Accommodation", "Accommodation")
                        .WithMany()
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("BnB.Core.Models.Payment", b =>
                {
                    b.HasOne("BnB.Core.Models.Guest", "Guest")
                        .WithMany("Payments")
                        .HasForeignKey("ConfirmationNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("BnB.Core.Models.RoomType", b =>
                {
                    b.HasOne("BnB.Core.Models.Property", "Property")
                        .WithMany("RoomTypes")
                        .HasForeignKey("PropertyAccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BnB.Core.Models.TravelAgentBooking", b =>
                {
                    b.HasOne("BnB.Core.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("ConfirmationNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnB.Core.Models.TravelAgency", "TravelAgency")
                        .WithMany("Bookings")
                        .HasForeignKey("TravelAgencyId");

                    b.Navigation("Guest");

                    b.Navigation("TravelAgency");
                });

            modelBuilder.Entity("BnB.Core.Models.CarAgency", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("BnB.Core.Models.Guest", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BnB.Core.Models.Property", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("BnB.Core.Models.TravelAgency", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
